name: Build latest version
on:
  push:
    branches:
      - master
      - main
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      # Install dependencies and run tests
      - uses: actions/checkout@v2
      - run: npm install
      # Build latest version
      - uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.BUILD_ACTOR_URL }}
          webhook_secret: ${{ secrets.APIFY_TOKEN }}
